module Location
  extend ActiveSupport::Concern
  
  
   
    
  def location_description
    case city 
    when "New York City"
      "NYC Metro Area"
    when "Los Angeles" 
      "Los Angeles, California Area"
    when "Chicago"
      "Chicago, IL"	
    when "Houston" 
      "Houston, TX"	
    when "Philadelphia" 
       "#{city}, PA"
    when "Phoenix"
      "#{city}, AZ"
    when "San Antonio"
      "TX"	
    when "San Diego" 
      "CA"
    when "Dallas"
      "Dallas/Fort Worth, Texas Area"	
    when "San Jose"
      "CA"
    when "Austin"
      "Austin, TX"	
    when "Jacksonville"
      "FL"	
    when "Indianapolis"
      "IN"	
    when "San Francisco"
      "CA"
    when "Columbus"
      "OH"	
    when "Fort Worth"
      "TX"	
    when "Charlotte"
      "NC"	
    when "Detroit"
      "MI"	
    when "El Paso"
      "TX"	
    when "Memphis"
      "TN"	
    when "Boston" 
      "MA"	
    when "Seattle"
      "WA"	
    when "Denver"
      "CO"	
    when "Washington"
      "DC"	
    when "Nashville-Davidson"
      "TN"	
    when "Baltimore"
      "Baltimore, Maryland Area"	
    when "Louisville-Jefferson"
      "KY"	
    when "Portland"
      "OR"	
    when "Oklahoma"
      "OK"	
    when "Milwaukee"
      "WI"	
    when "Las Vegas"
      "NV"	
    when "Albuquerque"
      "NM"
    when "Tucson"
      "AZ"	
    when "Fresno"
      "CA"
    when "Sacramento"
      "CA"
    when "Long Beach"
      "CA"
    when "Kansas-MO"
      "MO"	
    when "Mesa"
      "AZ"	
    when "Virginia Beach"
      "VA"	
    when "Atlanta"
      "GA"	
    when "Colorado Springs"
      "CO"	
    when "Raleigh"
      "NC"	
    when "Omaha"
      "NE"	
    when "Miami"
      "FL"	
    when "Oakland"
      "CA"
    when "Tulsa"
      "OK"	
    when "Minneapolis"
      "MN"	
    when "Cleveland"
      "OH"	
    when "Wichita"
      "KS"	
    when "Arlington"
      "TX"	
    when "New Orleans"
      "LA"	
    when "Bakersfield"
      "CA"	
    when "Tampa"
      "FL"	
    when "Honolulu"
      "HI"	
    when "Anaheim"
      "CA"	
    when "Aurora-CO" 
      "CO"	
    when "Santa Ana" 
      "CA"	
    when "St. Louis" 
      "MO"	
    when "Riverside" 
      "CA"	
    when "Corpus Christi" 
      "TX"	
    when "Pittsburgh" 
      "PA"	
    when "Lexington-Fayette" 
      "KY"	
    when "Anchorage"
      "AL"	
    when "Stockton" 
      "CA"	
    when "Cincinnati" 
      "OH"	
    when "St. Paul" 
      "MN"	
    when "Toledo" 
      "OH"	
    when "Newark" 
      "NJ"	
    when "Greensboro" 
      "NC"	
    when "Plano" 
      "TX"	
    when "Henderson"
      "NV"	
    when "Lincoln"
      "NE"	
    when "Buffalo"
      "NY"	
    when "Fort Wayne"
      "IN"	
    when "Jersey City"
      "NJ"	
    when "Chula Vista"
      "CA"	
    when "Orlando"
      "FL"	
    when "St. Petersburg"
      "FL"	
    when "Norfolk"
      "VA"	
    when "Chandler"
      "AZ"	
    when "Laredo"
      "TX"	
    when "Madison"
      "WI"
    when "Durham"
      "NC"	
    when "Lubbock"
      "TX"	
    when "Winston-Salem"
      "NC"	
    when "Garland"
      "TX"	
    when "Glendale"
      "AZ"	
    when "Hialeah"
      "FL"	
    when "Reno"
      "NV"
    when "Baton Rouge"
      "LA"	
    when "Irvine"
      "CA"	
    when "Chesapeake"
      "VA"	
    when "Irving"
      "TX"	
    when "Scottsdale"
      "AZ"	
    when "North Las Vegas"
      "NV"	
    when "Fremont"
      "CA"	
    when "Gilbert"
      "AZ"	
    when "San Bernardino"
      "CA"
    when "Boise"
      "ID"	
    when "Birmingham"
      "AL"	
    when "Rochester"
      "NY"	
    when "Richmond"
      "VA"	
    when "Spokane" 
        "WA"	
    when "Des Moines" 
      "IA"	
    when "Montgomery" 
      "AL"	
    when "Modesto" 
      "CA"	
    when "Fayetteville"
       "NC"	
    when "Tacoma"
      "WA"	
    when "Shreveport" 
      "LA"
    when "Fontana" 
      "CA"	
    when "Oxnard" 
      "CA"
    when "Aurora-IL" 
      "IL"	
    when "Moreno Valley" 
      "CA"	
    when "Akron"
      "OH"	
    when "Yonkers"
      "NY"	
    when "Columbus-GA" 
      "GA"	
    when "Augusta-Richmond"
      "GA"	
    when "Little Rock"
      "AR"	
    when "Amarillo"
      "TX"
    when "Mobile"
      "AL"
    when "Huntington Beach"
      "CA"	
    when "Glendale"
      "CA"	
    when "Grand Rapids"
      "MI"	
    when "Salt Lake"
      "UT"	
    when "Tallahassee"
      "FL"	
    when "Huntsville" 
      "AL"
    when "Worcester"
      "MA"	
    when "Knoxville"
      "TN"	
    when "Grand Prairie"
      "TX"	
    when "Newport News"
      "VA"	
    when "Brownsville"
      "TX"	
    when "Santa Clarita"
      "CA"	
    when "Overland Park"
      "KS"	
    when "Providence"
      "RI"	
    when "Jackson"
      "MS"	
    when "Garden Grove"
      "CA"	
    when "Oceanside"
      "CA"	
    when "Chattanooga"
      "TN"	
    when "Fort Lauderdale"
      "FL"	
    when "Rancho Cucamonga"
      "CA"	
    when "Santa Rosa"
      "CA"	
    when "Port St. Lucie"
      "FL"	
    when "Ontario"
      "CA"	
    when "Tempe"
      "AZ"	
    when "Vancouver"
      "WA"	
    when "Springfield-MO"
      "MO"	
    when "Cape Coral"
      "FL"	
    when "Pembroke Pines"
      "FL"	
    when "Sioux Falls"
      "SD"	
    when "Peoria"
      "AZ"	
    when "Lancaster"
      "CA"	
    when "Elk Grove"
      "CA"	
    when "Corona"
      "CA"
    when "Eugene"
      "OR"	
    when "Salem"
      "OR"	
    when "Palmdale"
      "CA"	
    when "Salinas"
      "CA"	
    when "Springfield-MA"
      "MA"	
    when "Pasadena-TX"
      "TX"	
    when "Rockford"
      "IL"	
    when "Pomona"
      "CA"
    when "Hayward"
      "CA"	
    when "Fort Collins"
      "CO"
    when "Joliet"
       "IL"	
    when "Escondido"
      "CA"	
    when "Kansas-KS"
      "KS"	
    when "Torrance"
      "CA"	
    when "Bridgeport"
      "CT"	
    when "Alexandria"
      "VA"	
    when "Sunnyvale"
      "CA"
    when "Cary"
      "NC"	
    when "Lakewood"
      "CO"
    when "Hollywood"
      "FL"	
    when "Paterson"
      "NJ"	
    when "Syracuse"
      "NY"	
    when "Naperville"
      "IL"	
    when "McKinney"
      "TX"	
    when "Mesquite"
      "TX"	
    when "Clarksville"
      "TN"	
    when "Savannah"
      "GA"	
    when "Dayton"
      "OH"	
    when "Orange"
      "CA"	
    when "Fullerton"
      "CA"	
    when "Pasadena"
      "CA"	
    when "Hampton"
      "VA"	
    when "McAllen"
      "TX"	
    when "Killeen"
      "TX"	
    when "Warren"
      "MI"	
    when "West Valley"
      "UT"	
    when "Columbia"
      "SC"	
    when "New Haven"
      "CT"	
    when "Sterling Heights"
      "MI"	
    when "Olathe"
      "KS"	
    when "Miramar"
      "FL"	
    when "Thousand Oaks"
      "CA"	
    when "Frisco"
      "TX"	
    when "Cedar Rapids"
      "IA"	
    when "Topeka"
      "KS"	
    when "Visalia"
      "CA"	
    when "Waco"
      "TX"
    end
  end
  
  module ClassMethods
    
    def cities_list
      ["New York City", "Los Angeles", "Chicago", "Houston", "Philadelphia", "Phoenix", "San Antonio", "San Diego", "Dallas", "San Jose", "Austin", "Jacksonville", "Indianapolis", "San Francisco", "Columbus", "Fort Worth", "Charlotte", "Detroit", "El Paso", "Memphis", "Boston", "Seattle", "Denver", "Washington", "Nashville-Davidson", "Baltimore", "Louisville-Jefferson", "Portland", "Oklahoma", "Milwaukee", "Las Vegas", "Albuquerque", "Tucson", "Fresno", "Sacramento", "Long Beach", "Kansas-MO", "Mesa", "Virginia Beach", "Atlanta", "Colorado Springs", "Raleigh", "Omaha", "Miami", "Oakland", "Tulsa", "Minneapolis", "Cleveland", "Wichita", "Arlington", "New Orleans", "Bakersfield", "Tampa", "Honolulu", "Anaheim", "Aurora-CO", "Santa Ana", "St. Louis", "Riverside", "Corpus Christi", "Pittsburgh", "Lexington-Fayette", "Anchorage", "Stockton", "Cincinnati", "St. Paul", "Toledo", "Newark", "Greensboro", "Plano", "Henderson", "Lincoln", "Buffalo", "Fort Wayne", "Jersey City", "Chula Vista", "Orlando", "St. Petersburg", "Norfolk", "Chandler", "Laredo", "Madison", "Durham", "Lubbock", "Winston-Salem", "Garland", "Glendale", "Hialeah", "Reno", "Baton Rouge", "Irvine", "Chesapeake", "Irving", "Scottsdale", "North Las Vegas", "Fremont", "Gilbert", "San Bernardino", "Boise", "Birmingham", "Rochester", "Richmond", "Spokane", "Des Moines", "Montgomery", "Modesto", "Fayetteville", "Tacoma", "Shreveport", "Fontana", "Oxnard", "Aurora-IL", "Moreno Valley", "Akron", "Yonkers", "Columbus-GA", "Augusta-Richmond", "Little Rock", "Amarillo", "Mobile", "Huntington Beach", "Glendale", "Grand Rapids", "Salt Lake City", "Tallahassee", "Huntsville", "Worcester", "Knoxville", "Grand Prairie", "Newport News", "Brownsville", "Santa Clarita", "Overland Park", "Providence", "Jackson", "Garden Grove", "Oceanside", "Chattanooga", "Fort Lauderdale", "Rancho Cucamonga", "Santa Rosa", "Port St. Lucie", "Ontario", "Tempe", "Vancouver", "Springfield-MO", "Cape Coral", "Pembroke Pines", "Sioux Falls", "Peoria", "Lancaster", "Elk Grove", "Corona", "Eugene", "Salem", "Palmdale", "Salinas", "Springfield-MA", "Pasadena-TX", "Rockford", "Pomona", "Hayward", "Fort Collins", "Joliet", "Escondido", "Kansas-KS", "Torrance", "Bridgeport", "Alexandria", "Sunnyvale", "Cary", "Lakewood", "Hollywood", "Paterson", "Syracuse", "Naperville", "McKinney", "Mesquite", "Clarksville", "Savannah", "Dayton", "Orange", "Fullerton", "Pasadena", "Hampton", "McAllen", "Killeen", "Warren", "West Valley", "Columbia", "New Haven", "Sterling Heights", "Olathe", "Miramar", "Thousand Oaks", "Frisco", "Cedar Rapids", "Topeka", "Visalia", "Waco"]
    end
    
    # def city_and_state
  #     case state
  #     when "New York City"
  #       "NY"
  #     when "Los Angeles"
  #       "CA"
  #     when "Chicago"
  #       "IL"
  #     when "Houston"
  #       "TX"
  #     when "Philadelphia"
  #        "PA"
  #     when "Phoenix"
  #       "AZ"
  #     when "San Antonio"
  #       "TX"
  #     when "San Diego"
  #       "CA"
  #     when "Dallas"
  #       "TX"
  #     when "San Jose"
  #       "CA"
  #     when "Austin"
  #       "TX"
  #     when "Jacksonville"
  #       "FL"
  #     when "Indianapolis"
  #       "IN"
  #     when "San Francisco"
  #       "CA"
  #     when "Columbus"
  #       "OH"
  #     when "Fort Worth"
  #       "TX"
  #     when "Charlotte"
  #       "NC"
  #     when "Detroit"
  #       "MI"
  #     when "El Paso"
  #       "TX"
  #     when "Memphis"
  #       "TN"
  #     when "Boston"
  #       "MA"
  #     when "Seattle"
  #       "WA"
  #     when "Denver"
  #       "CO"
  #     when "Washington"
  #       "DC"
  #     when "Nashville-Davidson"
  #       "TN"
  #     when "Baltimore"
  #       "MD"
  #     when "Louisville-Jefferson"
  #       "KY"
  #     when "Portland"
  #       "OR"
  #     when "Oklahoma"
  #       "OK"
  #     when "Milwaukee"
  #       "WI"
  #     when "Las Vegas"
  #       "NV"
  #     when "Albuquerque"
  #       "NM"
  #     when "Tucson"
  #       "AZ"
  #     when "Fresno"
  #       "CA"
  #     when "Sacramento"
  #       "CA"
  #     when "Long Beach"
  #       "CA"
  #     when "Kansas-MO"
  #       "MO"
  #     when "Mesa"
  #       "AZ"
  #     when "Virginia Beach"
  #       "VA"
  #     when "Atlanta"
  #       "GA"
  #     when "Colorado Springs"
  #       "CO"
  #     when "Raleigh"
  #       "NC"
  #     when "Omaha"
  #       "NE"
  #     when "Miami"
  #       "FL"
  #     when "Oakland"
  #       "CA"
  #     when "Tulsa"
  #       "OK"
  #     when "Minneapolis"
  #       "MN"
  #     when "Cleveland"
  #       "OH"
  #     when "Wichita"
  #       "KS"
  #     when "Arlington"
  #       "TX"
  #     when "New Orleans"
  #       "LA"
  #     when "Bakersfield"
  #       "CA"
  #     when "Tampa"
  #       "FL"
  #     when "Honolulu"
  #       "HI"
  #     when "Anaheim"
  #       "CA"
  #     when "Aurora-CO"
  #       "CO"
  #     when "Santa Ana"
  #       "CA"
  #     when "St. Louis"
  #       "MO"
  #     when "Riverside"
  #       "CA"
  #     when "Corpus Christi"
  #       "TX"
  #     when "Pittsburgh"
  #       "PA"
  #     when "Lexington-Fayette"
  #       "KY"
  #     when "Anchorage"
  #       "AL"
  #     when "Stockton"
  #       "CA"
  #     when "Cincinnati"
  #       "OH"
  #     when "St. Paul"
  #       "MN"
  #     when "Toledo"
  #       "OH"
  #     when "Newark"
  #       "NJ"
  #     when "Greensboro"
  #       "NC"
  #     when "Plano"
  #       "TX"
  #     when "Henderson"
  #       "NV"
  #     when "Lincoln"
  #       "NE"
  #     when "Buffalo"
  #       "NY"
  #     when "Fort Wayne"
  #       "IN"
  #     when "Jersey City"
  #       "NJ"
  #     when "Chula Vista"
  #       "CA"
  #     when "Orlando"
  #       "FL"
  #     when "St. Petersburg"
  #       "FL"
  #     when "Norfolk"
  #       "VA"
  #     when "Chandler"
  #       "AZ"
  #     when "Laredo"
  #       "TX"
  #     when "Madison"
  #       "WI"
  #     when "Durham"
  #       "NC"
  #     when "Lubbock"
  #       "TX"
  #     when "Winston-Salem"
  #       "NC"
  #     when "Garland"
  #       "TX"
  #     when "Glendale"
  #       "AZ"
  #     when "Hialeah"
  #       "FL"
  #     when "Reno"
  #       "NV"
  #     when "Baton Rouge"
  #       "LA"
  #     when "Irvine"
  #       "CA"
  #     when "Chesapeake"
  #       "VA"
  #     when "Irving"
  #       "TX"
  #     when "Scottsdale"
  #       "AZ"
  #     when "North Las Vegas"
  #       "NV"
  #     when "Fremont"
  #       "CA"
  #     when "Gilbert"
  #       "AZ"
  #     when "San Bernardino"
  #       "CA"
  #     when "Boise"
  #       "ID"
  #     when "Birmingham"
  #       "AL"
  #     when "Rochester"
  #       "NY"
  #     when "Richmond"
  #       "VA"
  #     when "Spokane"
  #         "WA"
  #     when "Des Moines"
  #       "IA"
  #     when "Montgomery"
  #       "AL"
  #     when "Modesto"
  #       "CA"
  #     when "Fayetteville"
  #        "NC"
  #     when "Tacoma"
  #       "WA"
  #     when "Shreveport"
  #       "LA"
  #     when "Fontana"
  #       "CA"
  #     when "Oxnard"
  #       "CA"
  #     when "Aurora-IL"
  #       "IL"
  #     when "Moreno Valley"
  #       "CA"
  #     when "Akron"
  #       "OH"
  #     when "Yonkers"
  #       "NY"
  #     when "Columbus-GA"
  #       "GA"
  #     when "Augusta-Richmond"
  #       "GA"
  #     when "Little Rock"
  #       "AR"
  #     when "Amarillo"
  #       "TX"
  #     when "Mobile"
  #       "AL"
  #     when "Huntington Beach"
  #       "CA"
  #     when "Glendale"
  #       "CA"
  #     when "Grand Rapids"
  #       "MI"
  #     when "Salt Lake"
  #       "UT"
  #     when "Tallahassee"
  #       "FL"
  #     when "Huntsville"
  #       "AL"
  #     when "Worcester"
  #       "MA"
  #     when "Knoxville"
  #       "TN"
  #     when "Grand Prairie"
  #       "TX"
  #     when "Newport News"
  #       "VA"
  #     when "Brownsville"
  #       "TX"
  #     when "Santa Clarita"
  #       "CA"
  #     when "Overland Park"
  #       "KS"
  #     when "Providence"
  #       "RI"
  #     when "Jackson"
  #       "MS"
  #     when "Garden Grove"
  #       "CA"
  #     when "Oceanside"
  #       "CA"
  #     when "Chattanooga"
  #       "TN"
  #     when "Fort Lauderdale"
  #       "FL"
  #     when "Rancho Cucamonga"
  #       "CA"
  #     when "Santa Rosa"
  #       "CA"
  #     when "Port St. Lucie"
  #       "FL"
  #     when "Ontario"
  #       "CA"
  #     when "Tempe"
  #       "AZ"
  #     when "Vancouver"
  #       "WA"
  #     when "Springfield-MO"
  #       "MO"
  #     when "Cape Coral"
  #       "FL"
  #     when "Pembroke Pines"
  #       "FL"
  #     when "Sioux Falls"
  #       "SD"
  #     when "Peoria"
  #       "AZ"
  #     when "Lancaster"
  #       "CA"
  #     when "Elk Grove"
  #       "CA"
  #     when "Corona"
  #       "CA"
  #     when "Eugene"
  #       "OR"
  #     when "Salem"
  #       "OR"
  #     when "Palmdale"
  #       "CA"
  #     when "Salinas"
  #       "CA"
  #     when "Springfield-MA"
  #       "MA"
  #     when "Pasadena-TX"
  #       "TX"
  #     when "Rockford"
  #       "IL"
  #     when "Pomona"
  #       "CA"
  #     when "Hayward"
  #       "CA"
  #     when "Fort Collins"
  #       "CO"
  #     when "Joliet"
  #        "IL"
  #     when "Escondido"
  #       "CA"
  #     when "Kansas-KS"
  #       "KS"
  #     when "Torrance"
  #       "CA"
  #     when "Bridgeport"
  #       "CT"
  #     when "Alexandria"
  #       "VA"
  #     when "Sunnyvale"
  #       "CA"
  #     when "Cary"
  #       "NC"
  #     when "Lakewood"
  #       "CO"
  #     when "Hollywood"
  #       "FL"
  #     when "Paterson"
  #       "NJ"
  #     when "Syracuse"
  #       "NY"
  #     when "Naperville"
  #       "IL"
  #     when "McKinney"
  #       "TX"
  #     when "Mesquite"
  #       "TX"
  #     when "Clarksville"
  #       "TN"
  #     when "Savannah"
  #       "GA"
  #     when "Dayton"
  #       "OH"
  #     when "Orange"
  #       "CA"
  #     when "Fullerton"
  #       "CA"
  #     when "Pasadena"
  #       "CA"
  #     when "Hampton"
  #       "VA"
  #     when "McAllen"
  #       "TX"
  #     when "Killeen"
  #       "TX"
  #     when "Warren"
  #       "MI"
  #     when "West Valley"
  #       "UT"
  #     when "Columbia"
  #       "SC"
  #     when "New Haven"
  #       "CT"
  #     when "Sterling Heights"
  #       "MI"
  #     when "Olathe"
  #       "KS"
  #     when "Miramar"
  #       "FL"
  #     when "Thousand Oaks"
  #       "CA"
  #     when "Frisco"
  #       "TX"
  #     when "Cedar Rapids"
  #       "IA"
  #     when "Topeka"
  #       "KS"
  #     when "Visalia"
  #       "CA"
  #     when "Waco"
  #       "TX"
  #     end
  #   end
    
  end
  
end	